import { pipe } from 'fp-ts/lib/function'
import * as F from '../src/icloud/drive/cache/cachef'

import { DriveDetails } from '../src/icloud/drive/types'
import { logger } from '../src/lib/logging'
// import { DriveItemFolderDetails } from '../src/icloud/drive/driveResponseType'
import * as E from 'fp-ts/lib/Either'

const rootDetails: DriveDetails = {
    "dateCreated": new Date("2021-07-26T19:34:15Z"),
    "drivewsid": "FOLDER::com.apple.CloudDocs::root",
    "docwsid": "root",
    "zone": "com.apple.CloudDocs",
    "name": "",
    "etag": "18",
    "type": "FOLDER",
    "assetQuota": 30,
    "fileCount": 3,
    "shareCount": 0,
    "shareAliasCount": 0,
    "directChildrenCount": 5,
    "items": [
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::com.apple.CloudDocs::0E41ADBB-C07E-4AE1-A043-ACF74280D646",
            "docwsid": "0E41ADBB-C07E-4AE1-A043-ACF74280D646",
            "zone": "com.apple.CloudDocs",
            "name": "Desktop",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "g",
            "type": "FOLDER",
            "assetQuota": 0,
            "fileCount": 1,
            "shareCount": 0,
            "shareAliasCount": 0,
            "directChildrenCount": 1
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::com.apple.CloudDocs::861A7021-AFC0-45AB-8A0B-6595AEBBBA93",
            "docwsid": "861A7021-AFC0-45AB-8A0B-6595AEBBBA93",
            "zone": "com.apple.CloudDocs",
            "name": "Documents",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "l",
            "type": "FOLDER",
            "assetQuota": 0,
            "fileCount": 1,
            "shareCount": 0,
            "shareAliasCount": 0,
            "directChildrenCount": 1
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::com.apple.CloudDocs::47AD1961-C2FA-4240-A531-83E2D2C905E8",
            "docwsid": "47AD1961-C2FA-4240-A531-83E2D2C905E8",
            "zone": "com.apple.CloudDocs",
            "name": "Downloads",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "9",
            "type": "FOLDER",
            "assetQuota": 0,
            "fileCount": 0,
            "shareCount": 0,
            "shareAliasCount": 0,
            "directChildrenCount": 0
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::iCloud.md.obsidian::documents",
            "docwsid": "documents",
            "zone": "iCloud.md.obsidian",
            "name": "Obsidian",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "ca",
            "type": "APP_LIBRARY",
            "maxDepth": "ANY",
            "icons": [
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.md.obsidian&field=icon120x120_iOS",
                    "type": "IOS",
                    "size": 120
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.md.obsidian&field=icon80x80_iOS",
                    "type": "IOS",
                    "size": 80
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.md.obsidian&field=icon40x40_iOS",
                    "type": "IOS",
                    "size": 40
                }
            ],
            "supportedExtensions": [
                "sd2",
                "xlt",
                "ksh",
                "xlw",
                "m75",
                "der",
                "raf",
                "xml",
                "shtml",
                "pict",
                "kth",
                "3g2",
                "ram",
                "itms",
                "aa",
                "ai",
                "raw",
                "diff",
                "panic",
                "sda",
                "sdd",
                "as",
                "sdc",
                "au",
                "ypp",
                "sdp",
                "sf2",
                "3fr",
                "xltx",
                "aac",
                "hang",
                "sdv",
                "rbw",
                "aaf",
                "sdw",
                "wma",
                "cel",
                "pptm",
                "sea",
                "zsh",
                "tga",
                "savedsearch",
                "ac3",
                "ppsx",
                "cer",
                "xltm",
                "epub",
                "bz",
                "jpeg",
                "aax",
                "j2c",
                "wmp",
                "flc",
                "3gp",
                "dotx",
                "cc",
                "xlsx",
                "wmv",
                "scpt",
                "minc",
                "j2k",
                "fli",
                "wmx",
                "abc",
                "c",
                "tgz",
                "f",
                "h",
                "dylib",
                "i",
                "hpp",
                "dotm",
                "l",
                "cp",
                "m",
                "lxx",
                "icns",
                "ppsm",
                "o",
                "flv",
                "r",
                "s",
                "xlsm",
                "spin",
                "y",
                "z",
                "xlsb",
                "dif",
                "potm",
                "hqx",
                "jscript",
                "tif",
                "dv",
                "sgi",
                "adb",
                "ada",
                "pas",
                "pax",
                "pptx",
                "cdda",
                "ads",
                "ulw",
                "pntg",
                "smil",
                "for",
                "pch",
                "applescript",
                "json",
                "class",
                "sit",
                "pct",
                "htm",
                "dll",
                "mobile",
                "dls",
                "fpx",
                "pdf",
                "gz",
                "key-tef",
                "potx",
                "hh",
                "c++",
                "bin",
                "hp",
                "pef",
                "pem",
                "text",
                "dng",
                "ii",
                "defs",
                "afploc",
                "eps",
                "pfa",
                "odb",
                "pfb",
                "odc",
                "odf",
                "tcsh",
                "odg",
                "lpdf",
                "odi",
                "yxx",
                "odm",
                "doc",
                "odp",
                "ph3",
                "ulaw",
                "ph4",
                "odt",
                "ods",
                "aif",
                "template",
                "pfx",
                "dot",
                "js",
                "smf",
                "fileloc",
                "smi",
                "xhtm",
                "sml",
                "erf",
                "shutdownstall",
                "sidx",
                "snd",
                "hxx",
                "gzip",
                "dlyan",
                "mobileconfig",
                "url",
                "wvx",
                "php",
                "scriptable",
                "lm",
                "bmp",
                "newsloc",
                "php4",
                "pic",
                "nef",
                "mpga",
                "php3",
                "f4a",
                "pages",
                "etd",
                "f4b",
                "mi",
                "mm",
                "cr2",
                "cpp",
                "f4p",
                "mpg4",
                "f4v",
                "sr2",
                "mpeg",
                "pkpass",
                "tiff",
                "inetloc",
                "amr",
                "f77",
                "gpurestart",
                "pkg",
                "adts",
                "tbz2",
                "tsv",
                "kar",
                "ttc",
                "crt",
                "srf",
                "ttf",
                "crw",
                "gtar",
                "pf",
                "pls",
                "srw",
                "jnlp",
                "csh",
                "pl",
                "f90",
                "pm",
                "ps",
                "f95",
                "textclipping",
                "mobileprovision",
                "csv",
                "py",
                "mpkg",
                "cpgz",
                "nii",
                "crash",
                "patch",
                "rmvb",
                "exe",
                "java",
                "docm",
                "jar",
                "band",
                "exp",
                "exr",
                "jav",
                "app",
                "std",
                "qt",
                "stc",
                "png",
                "sti",
                "vcard",
                "javascript",
                "ra",
                "rb",
                "stw",
                "rm",
                "ftploc",
                "phtml",
                "omf",
                "mid",
                "mig",
                "mii",
                "webarchive",
                "rss",
                "pot",
                "sh",
                "key",
                "svg",
                "rtf",
                "arw",
                "docx",
                "txt",
                "pps",
                "inss",
                "asf",
                "ppt",
                "m3u8",
                "cpio",
                "ts",
                "lid",
                "asx",
                "numbers",
                "icc",
                "rw2",
                "p12",
                "icm",
                "ico",
                "ul",
                "ics",
                "sxd",
                "sxc",
                "svgz",
                "uu",
                "cxx",
                "sxg",
                "sxi",
                "qti",
                "xar",
                "sxm",
                "pch++",
                "bwf",
                "sxw",
                "qtif",
                "rtfd",
                "qtz",
                "jfx",
                "psd",
                "xbm",
                "aiff",
                "rwl",
                "aifc",
                "wave",
                "avi",
                "wm",
                "bz2",
                "orf",
                "mnc",
                "numbers-tef",
                "war",
                "wav",
                "mp2",
                "wax",
                "xhtml",
                "mp4",
                "mp3",
                "bash",
                "provisionprofile",
                "dfont",
                "nmbtemplate",
                "aupreset",
                "lmm",
                "mos",
                "midi",
                "ym",
                "mov",
                "otc",
                "zip",
                "otf",
                "oth",
                "otg",
                "mpe",
                "pages-tef",
                "oti",
                "mpg",
                "otp",
                "mpo",
                "ott",
                "ots",
                "nrw",
                "xfd",
                "suit",
                "pictclipping",
                "pwl",
                "3gp2",
                "m15",
                "plist",
                "configprofile",
                "vcf",
                "vcs",
                "fdf",
                "lpp",
                "sitx",
                "mrw",
                "xht",
                "dae",
                "3gpp",
                "gbproj",
                "html",
                "xip",
                "webloc",
                "tar",
                "fff",
                "jp2",
                "edn",
                "mailloc",
                "vcal",
                "m2v",
                "shtm",
                "icloud",
                "gif",
                "vfw",
                "xfdf",
                "caf",
                "h++",
                "tbz",
                "m3u",
                "dcm",
                "dcr",
                "ymm",
                "m4b",
                "m4a",
                "jpe",
                "jpg",
                "jpf",
                "inl",
                "m4p",
                "m4r",
                "xla",
                "m4v",
                "jpx",
                "efx",
                "xls"
            ],
            "supportedTypes": [
                "net.daringfireball.markdown",
                "public.data",
                "public.content"
            ]
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::iCloud.dk.simonbs.Scriptable::documents",
            "docwsid": "documents",
            "zone": "iCloud.dk.simonbs.Scriptable",
            "name": "Scriptable",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "e",
            "type": "APP_LIBRARY",
            "maxDepth": "ANY",
            "icons": [
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.dk.simonbs.Scriptable&field=icon120x120_iOS",
                    "type": "IOS",
                    "size": 120
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.dk.simonbs.Scriptable&field=icon80x80_iOS",
                    "type": "IOS",
                    "size": 80
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.dk.simonbs.Scriptable&field=icon40x40_iOS",
                    "type": "IOS",
                    "size": 40
                }
            ],
            "supportedExtensions": [
                "sd2",
                "xlt",
                "ksh",
                "xlw",
                "m75",
                "der",
                "scptd",
                "raf",
                "xml",
                "saver",
                "shtml",
                "pict",
                "kth",
                "3g2",
                "ram",
                "itms",
                "aa",
                "ai",
                "raw",
                "diff",
                "panic",
                "sda",
                "sdd",
                "as",
                "sdc",
                "au",
                "ypp",
                "sdp",
                "sf2",
                "3fr",
                "xltx",
                "aac",
                "hang",
                "sdv",
                "rbw",
                "aaf",
                "sdw",
                "wma",
                "cel",
                "pptm",
                "wdgt",
                "sea",
                "zsh",
                "tga",
                "savedsearch",
                "ac3",
                "ppsx",
                "cer",
                "xltm",
                "epub",
                "bz",
                "jpeg",
                "aax",
                "j2c",
                "wmp",
                "flc",
                "3gp",
                "dotx",
                "cc",
                "xlsx",
                "wmv",
                "scpt",
                "minc",
                "j2k",
                "fli",
                "wmx",
                "abc",
                "c",
                "tgz",
                "f",
                "h",
                "dylib",
                "i",
                "hpp",
                "xpc",
                "dotm",
                "l",
                "cp",
                "m",
                "lxx",
                "icns",
                "ppsm",
                "o",
                "flv",
                "r",
                "s",
                "xlsm",
                "spin",
                "y",
                "z",
                "xlsb",
                "dif",
                "potm",
                "hqx",
                "jscript",
                "tif",
                "dv",
                "sgi",
                "wflow",
                "adb",
                "ada",
                "pas",
                "pax",
                "pptx",
                "cdda",
                "ads",
                "ulw",
                "pntg",
                "smil",
                "for",
                "pch",
                "applescript",
                "json",
                "class",
                "sit",
                "pct",
                "htm",
                "dll",
                "iconset",
                "mobile",
                "dls",
                "fpx",
                "pdf",
                "gz",
                "key-tef",
                "potx",
                "hh",
                "c++",
                "bin",
                "hp",
                "pef",
                "pem",
                "text",
                "dng",
                "ii",
                "defs",
                "afploc",
                "pluginkit",
                "eps",
                "pfa",
                "odb",
                "pfb",
                "odc",
                "odf",
                "tcsh",
                "odg",
                "lpdf",
                "odi",
                "yxx",
                "odm",
                "doc",
                "odp",
                "ph3",
                "ulaw",
                "ph4",
                "odt",
                "ods",
                "aif",
                "template",
                "pfx",
                "dot",
                "js",
                "smf",
                "fileloc",
                "smi",
                "xhtm",
                "sml",
                "erf",
                "bundle",
                "shutdownstall",
                "sidx",
                "snd",
                "hxx",
                "gzip",
                "dlyan",
                "mobileconfig",
                "menu",
                "url",
                "framework",
                "wvx",
                "php",
                "mdimporter",
                "scriptable",
                "lm",
                "bmp",
                "newsloc",
                "php4",
                "dist",
                "pic",
                "nef",
                "mpga",
                "php3",
                "f4a",
                "pages",
                "etd",
                "f4b",
                "md",
                "mi",
                "mm",
                "cr2",
                "cpp",
                "f4p",
                "mpg4",
                "f4v",
                "sr2",
                "mpeg",
                "pkpass",
                "tiff",
                "avchd",
                "inetloc",
                "amr",
                "f77",
                "gpurestart",
                "pkg",
                "adts",
                "tbz2",
                "tsv",
                "kar",
                "ttc",
                "crt",
                "srf",
                "ttf",
                "crw",
                "gtar",
                "pf",
                "pls",
                "srw",
                "jnlp",
                "csh",
                "pl",
                "f90",
                "pm",
                "css",
                "ps",
                "f95",
                "xmind",
                "textclipping",
                "mobileprovision",
                "csv",
                "py",
                "mpkg",
                "cpgz",
                "pml",
                "nii",
                "crash",
                "patch",
                "qlgenerator",
                "rmvb",
                "exe",
                "java",
                "docm",
                "jar",
                "band",
                "exp",
                "exr",
                "jav",
                "app",
                "std",
                "qt",
                "stc",
                "distz",
                "png",
                "sti",
                "vcard",
                "javascript",
                "ra",
                "rb",
                "stw",
                "rm",
                "ftploc",
                "phtml",
                "omf",
                "mid",
                "mig",
                "mii",
                "webarchive",
                "rss",
                "pot",
                "sh",
                "markdown",
                "key",
                "svg",
                "rtf",
                "arw",
                "docx",
                "txt",
                "pps",
                "inss",
                "plugin",
                "asf",
                "ppt",
                "m3u8",
                "cpio",
                "ts",
                "lid",
                "asx",
                "numbers",
                "icc",
                "rw2",
                "p12",
                "icm",
                "ico",
                "ul",
                "webplugin",
                "ics",
                "sxd",
                "sxc",
                "svgz",
                "uu",
                "cxx",
                "sxg",
                "sxi",
                "qti",
                "xar",
                "sxm",
                "pch++",
                "bwf",
                "sxw",
                "qtif",
                "rtfd",
                "qtz",
                "jfx",
                "fpbf",
                "psd",
                "xbm",
                "aiff",
                "rwl",
                "aifc",
                "wave",
                "avi",
                "wm",
                "bz2",
                "orf",
                "mnc",
                "numbers-tef",
                "war",
                "wav",
                "mp2",
                "wax",
                "xhtml",
                "mp4",
                "mp3",
                "bash",
                "provisionprofile",
                "dfont",
                "nmbtemplate",
                "aupreset",
                "lmm",
                "prefpane",
                "mos",
                "midi",
                "ym",
                "mov",
                "otc",
                "appex",
                "zip",
                "otf",
                "oth",
                "otg",
                "mpe",
                "ibooks",
                "slidesaver",
                "pages-tef",
                "oti",
                "mpg",
                "otp",
                "mpo",
                "ott",
                "ots",
                "nrw",
                "xfd",
                "suit",
                "imovielibrary",
                "pictclipping",
                "pwl",
                "3gp2",
                "m15",
                "plist",
                "configprofile",
                "vcf",
                "vcs",
                "fdf",
                "lpp",
                "sitx",
                "mrw",
                "xht",
                "dae",
                "3gpp",
                "gbproj",
                "theater",
                "html",
                "xip",
                "webloc",
                "tar",
                "fff",
                "webp",
                "jp2",
                "edn",
                "mailloc",
                "vcal",
                "m2v",
                "shtm",
                "icloud",
                "gif",
                "vfw",
                "xfdf",
                "caf",
                "h++",
                "tbz",
                "m3u",
                "dcm",
                "dcr",
                "shortcut",
                "ymm",
                "m4b",
                "m4a",
                "jpe",
                "jpg",
                "jpf",
                "inl",
                "m4p",
                "m4r",
                "xla",
                "m4v",
                "jpx",
                "efx",
                "xls"
            ],
            "supportedTypes": [
                "public.item",
                "com.netscape.javascript-source",
                "dk.simonbs.scriptable.scriptable"
            ]
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::iCloud.is.workflow.my.workflows::documents",
            "docwsid": "documents",
            "zone": "iCloud.is.workflow.my.workflows",
            "name": "Shortcuts",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "etag": "a",
            "type": "APP_LIBRARY",
            "maxDepth": "ANY",
            "icons": [
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.is.workflow.my.workflows&field=icon120x120_iOS",
                    "type": "IOS",
                    "size": 120
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.is.workflow.my.workflows&field=icon80x80_iOS",
                    "type": "IOS",
                    "size": 80
                },
                {
                    "url": "https://p46-drivews.icloud.com/getIcons?id=iCloud.is.workflow.my.workflows&field=icon40x40_iOS",
                    "type": "IOS",
                    "size": 40
                }
            ],
            "supportedExtensions": [
                "shortcut",
                "wflow"
            ],
            "supportedTypes": [
                "com.apple.shortcut",
                "com.apple.shortcuts.workflow-file"
            ]
        },
        {
            "dateCreated": new Date("2021-07-26T19:34:15Z"),
            "drivewsid": "FOLDER::com.apple.CloudDocs::EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
            "docwsid": "EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
            "zone": "com.apple.CloudDocs",
            "name": "test",
            "parentId": "FOLDER::com.apple.CloudDocs::root",
            "isChainedToParent": true,
            "etag": "19",
            "type": "FOLDER",
            "assetQuota": 30,
            "fileCount": 1,
            "shareCount": 0,
            "shareAliasCount": 0,
            "directChildrenCount": 2
        }
    ],
    "numberOfItems": 7,
    "status": "OK"
}

const testDetails: DriveDetails = {
    "dateCreated": new Date("2021-09-11T19:46:45Z"),
    "drivewsid": "FOLDER::com.apple.CloudDocs::EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
    "docwsid": "EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
    "zone": "com.apple.CloudDocs",
    "name": "test",
    "parentId": "FOLDER::com.apple.CloudDocs::root",
    "isChainedToParent": true,
    "etag": "19",
    "type": "FOLDER",
    "assetQuota": 30,
    "fileCount": 1,
    "shareCount": 0,
    "shareAliasCount": 0,
    "directChildrenCount": 2,
    "items": [
      {
        "dateCreated": new Date("2021-09-11T19:46:45Z"),
        "drivewsid": "FOLDER::com.apple.CloudDocs::A67DC7B6-30AA-4133-BE86-3CEADBC48DC7",
        "docwsid": "A67DC7B6-30AA-4133-BE86-3CEADBC48DC7",
        "zone": "com.apple.CloudDocs",
        "name": "test1",
        "parentId": "FOLDER::com.apple.CloudDocs::EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
        "isChainedToParent": true,
        "etag": "17",
        "type": "FOLDER",
        "assetQuota": 30,
        "fileCount": 1,
        "shareCount": 0,
        "shareAliasCount": 0,
        "directChildrenCount": 2
      },
      {
        "dateCreated": new Date("2021-09-11T19:46:45Z"),
        "drivewsid": "FOLDER::com.apple.CloudDocs::05CB419C-3B70-4AE1-8DBE-5DE166E72D9C",
        "docwsid": "05CB419C-3B70-4AE1-8DBE-5DE166E72D9C",
        "zone": "com.apple.CloudDocs",
        "name": "test2",
        "parentId": "FOLDER::com.apple.CloudDocs::EFDC48C5-5917-4A68-B11A-057F63EFD4C8",
        "isChainedToParent": true,
        "etag": "r",
        "type": "FOLDER",
        "assetQuota": 0,
        "fileCount": 0,
        "shareCount": 0,
        "shareAliasCount": 0,
        "directChildrenCount": 0
      }
    ],
    "numberOfItems": 2,
    "status": "OK"
  }

describe('drive-cache', () => {
    it('1', () => {
        const cache = F.cachef()

        logger.info(
            pipe(
                cache,
                F.putDetails(rootDetails),
                E.chain(F.putDetails(testDetails)),
                E.chain(F.putDetails({...rootDetails, etag: 'new1'})),
            )
        )
    })
})