import assert from 'assert'
import * as A from 'fp-ts/lib/Array'
import { flow, pipe } from 'fp-ts/lib/function'
import * as NA from 'fp-ts/lib/NonEmptyArray'
import * as RA from 'fp-ts/lib/ReadonlyArray'
import * as SRTE from 'fp-ts/lib/StateReaderTaskEither'
import { NormalizedPath } from '../../../cli/cli-drive/cli-drive-actions/helpers'
import { err } from '../../../lib/errors'
import * as V from '../cache/cachef/GetByPathResultValid'
import * as DF from '../fdrive'
import { Details, DetailsRegular, DriveChildrenItemFile, fileName, Root } from '../requests/types/types'
import { lsss } from './lsss'
