import * as A from 'fp-ts/lib/Array'
import * as E from 'fp-ts/lib/Either'
import { flow, pipe } from 'fp-ts/lib/function'
import * as O from 'fp-ts/lib/Option'
import * as TE from 'fp-ts/TaskEither'
import * as t from 'io-ts'
import { defaultCountryCode } from '../../../config'
import { err, UnexpectedResponse } from '../../../lib/errors'
import { HttpResponse } from '../../../lib/http/fetch-client'
import { getHeader } from '../../../lib/http/http-headers'
import { arrayFromOption } from '../../../lib/util'
import * as NM from '../../drive/api/newbuilder'
import { BasicState } from '../../drive/requests/request'
import { applyCookiesToSession, HttpRequestConfig } from '../../session/session-http'
import { headers } from '../../session/session-http-headers'
import { authorizationHeaders } from '../headers'
import { applyAuthorizationResponse } from '../session'
import { AccountLoginResponseBody } from '../types'
